export type Lang = "fr" | "ar";

export const contact = {
  name: "CASA FIRMA",
  address: "Route Somaa, Tazarka 8024, Tunisie",
  phone: "+216 50 792 037",
  tel: "tel:+21650792037",
  whatsapp: "https://wa.me/21650792037",
  instagram: "https://www.instagram.com/casafirma/",
  instagramHandle: "@casafirma",
  maps: "https://www.google.com/maps/search/?api=1&query=Route+Somaa%2C+Tazarka+8024%2C+Tunisie",
};

export const nav = {
  fr: [
    { id: "accueil", label: "Accueil" },
    { id: "hebergements", label: "Hébergements" },
    { id: "experience", label: "Expérience" },
    { id: "galerie", label: "Galerie" },
    { id: "localisation", label: "Localisation" },
    { id: "contact", label: "Contact" },
  ],
  ar: [
    { id: "accueil", label: "الرئيسية" },
    { id: "hebergements", label: "الإقامات" },
    { id: "experience", label: "التجربة" },
    { id: "galerie", label: "معرض الصور" },
    { id: "localisation", label: "الموقع" },
    { id: "contact", label: "اتصل بنا" },
  ],
};

export const t = {
  fr: {
    reserve: "Réserver",
    hero: {
      eyebrow: "Maison d’hôtes • Tazarka • Tunisie",
      title1: "Votre échappée",
      title2: "méditerranéenne.",
      sub: "Un lieu privé pour ralentir, respirer et profiter.",
      text: "Découvrez CASA FIRMA, un cadre paisible à Tazarka pensé pour profiter de moments de détente en famille ou entre amis.",
      cta1: "Réserver votre séjour",
      cta2: "Découvrir Casa Firma",
      scroll: "Défiler",
    },
    intro: {
      eyebrow: "Bienvenue à Casa Firma",
      title1: "Un lieu pensé",
      title2: "pour se retrouver.",
      text: "CASA FIRMA vous accueille à Tazarka dans un cadre privé et confortable, idéal pour profiter de la mer, du calme et de moments partagés.",
      imageAlt: "Salon lumineux ouvert sur le jardin d’une maison méditerranéenne",
    },
    stays: {
      eyebrow: "Nos hébergements",
      title1: "Choisissez votre",
      title2: "espace.",
      cta: "Voir l’hébergement",
      items: [
        {
          name: "Villa S+3",
          badge: "",
          specs: ["Jusqu’à 9 personnes", "3 chambres", "Climatisée"],
          text: "Une villa spacieuse pensée pour les séjours en famille ou entre amis.",
          alt: "Façade d’une villa méditerranéenne blanche avec porte en arc et oliviers",
        },
        {
          name: "Bungalow S+2",
          badge: "2 bungalows S+2",
          specs: ["Jusqu’à 6 personnes", "2 chambres", "Climatisé"],
          text: "Un espace confortable et privé pour profiter pleinement de votre séjour.",
          alt: "Bungalow méditerranéen avec terrasse ombragée et bougainvillier",
        },
      ],
    },
    features: {
      eyebrow: "L’expérience privée",
      title1: "Votre espace.",
      title2: "Votre rythme.",
      items: [
        { name: "Piscines privées", text: "Profitez de votre propre espace extérieur pour vous détendre." },
        { name: "Grand jardin", text: "Un espace extérieur agréable pour partager des moments en plein air." },
        { name: "Espace barbecue", text: "Un coin barbecue pour les repas et moments conviviaux." },
        { name: "Confort & intimité", text: "Un cadre pensé pour profiter d’un séjour privé et reposant." },
        { name: "Wi-Fi", text: "Restez connecté lorsque vous en avez besoin." },
        { name: "Climatisation", text: "Des espaces climatisés pour votre confort." },
        { name: "Cuisine", text: "Des espaces équipés pour préparer vos repas." },
        { name: "Parking", text: "Un espace de stationnement disponible sur place." },
      ],
    },
    location: {
      eyebrow: "Tazarka",
      title1: "À quelques minutes",
      title2: "de la mer.",
      text: "Profitez de la douceur de Tazarka et de son ambiance côtière, tout en séjournant dans un espace privé et confortable.",
      place: "Tazarka",
      country: "Tunisie",
      alt: "Côte tunisienne au coucher du soleil avec mer turquoise et barque de pêche",
    },
    gallery: {
      eyebrow: "Galerie",
      title1: "Un avant-goût",
      title2: "de Casa Firma.",
      note: "Photographies temporaires — elles seront remplacées par les photos réelles de la propriété.",
      cta: "Suivre @casafirma sur Instagram",
    },
    experience: {
      title: "Plus qu’un séjour.",
      text: "Un endroit pour ralentir, profiter des proches et créer des souvenirs autour de la mer, du soleil et du confort d’une maison privée.",
      items: [
        { name: "Se détendre", text: "Piscine, jardin et espaces extérieurs.", alt: "Piscine privée bordée d’oliviers" },
        { name: "Partager", text: "Des espaces adaptés aux moments en famille ou entre amis.", alt: "Table dressée en extérieur sous une pergola" },
        { name: "Découvrir", text: "Profiter de Tazarka et de son environnement côtier.", alt: "Porte bleue traditionnelle sur mur blanc" },
      ],
    },
    booking: {
      title1: "Votre séjour",
      title2: "commence ici.",
      text: "Pour connaître les disponibilités et organiser votre séjour, contactez CASA FIRMA directement.",
      wa: "Réserver sur WhatsApp",
      call: "Appeler",
    },
    contact: {
      eyebrow: "Contact",
      title1: "Retrouvez Casa Firma",
      title2: "à Tazarka.",
      addressLabel: "Adresse",
      phoneLabel: "Téléphone",
      instaLabel: "Instagram",
      maps: "Ouvrir Google Maps",
      call: "Appeler",
      wa: "WhatsApp",
      insta: "Suivre sur Instagram",
      mapNote: "Emplacement approximatif — ouvrez Google Maps pour l’itinéraire.",
    },
    footer: {
      tagline: "Maison d’hôtes",
      city: "Tazarka, Tunisie",
      links: "Navigation",
      social: "Réseaux",
      contact: "Contact",
      rights: "© 2026 CASA FIRMA",
    },
  },

  ar: {
    reserve: "احجز",
    hero: {
      eyebrow: "دار ضيافة • تازركة • تونس",
      title1: "إقامتك المتوسطية",
      title2: "تبدأ من هنا.",
      sub: "فضاء خاص للاسترخاء والتنفس والاستمتاع.",
      text: "اكتشف CASA FIRMA في تازركة، فضاء خاص وهادئ للاستمتاع بالبحر والراحة واللحظات الجميلة مع العائلة والأصدقاء.",
      cta1: "احجز إقامتك",
      cta2: "اكتشف كازا فيرما",
      scroll: "اسحب للأسفل",
    },
    intro: {
      eyebrow: "مرحبًا بكم في كازا فيرما",
      title1: "مكان مصمم",
      title2: "للقاء الأحبة.",
      text: "يستقبلكم CASA FIRMA في تازركة في إطار خاص ومريح، مثالي للاستمتاع بالبحر والهدوء واللحظات المشتركة.",
      imageAlt: "فضاء معيشة مضيء يطل على حديقة منزل متوسطي",
    },
    stays: {
      eyebrow: "الإقامات",
      title1: "اختر",
      title2: "فضاءك.",
      cta: "عرض الإقامة",
      items: [
        {
          name: "فيلا S+3",
          badge: "",
          specs: ["حتى 9 أشخاص", "3 غرف", "مكيّفة"],
          text: "فيلا واسعة مصممة للإقامات مع العائلة أو الأصدقاء.",
          alt: "واجهة فيلا متوسطية بيضاء بباب مقوّس وأشجار زيتون",
        },
        {
          name: "بنغالو S+2",
          badge: "بنغالوهان S+2",
          specs: ["حتى 6 أشخاص", "غرفتان", "مكيّف"],
          text: "فضاء مريح وخاص للاستمتاع الكامل بإقامتكم.",
          alt: "بنغالو متوسطي بشرفة مظللة وأزهار الجهنمية",
        },
      ],
    },
    features: {
      eyebrow: "التجربة الخاصة",
      title1: "فضاؤك.",
      title2: "إيقاعك.",
      items: [
        { name: "مسابح خاصة", text: "استمتع بفضائك الخارجي الخاص للاسترخاء." },
        { name: "حديقة واسعة", text: "فضاء خارجي لطيف لمشاركة اللحظات في الهواء الطلق." },
        { name: "منطقة للشواء", text: "ركن للشواء من أجل الوجبات واللحظات الودية." },
        { name: "راحة وخصوصية", text: "إطار مصمم لإقامة خاصة ومريحة." },
        { name: "واي فاي", text: "ابقَ متصلاً عند الحاجة." },
        { name: "تكييف", text: "فضاءات مكيّفة من أجل راحتكم." },
        { name: "مطبخ", text: "فضاءات مجهزة لتحضير وجباتكم." },
        { name: "موقف سيارات", text: "مكان لركن السيارة متوفر في عين المكان." },
      ],
    },
    location: {
      eyebrow: "تازركة",
      title1: "على بعد دقائق",
      title2: "من البحر.",
      text: "استمتع بلطف تازركة وأجوائها الساحلية، مع الإقامة في فضاء خاص ومريح.",
      place: "تازركة",
      country: "تونس",
      alt: "الساحل التونسي عند الغروب مع بحر فيروزي وقارب صيد",
    },
    gallery: {
      eyebrow: "معرض الصور",
      title1: "لمحة",
      title2: "عن كازا فيرما.",
      note: "صور مؤقتة — سيتم استبدالها بالصور الحقيقية للإقامة.",
      cta: "تابعنا على إنستغرام @casafirma",
    },
    experience: {
      title: "أكثر من مجرد إقامة.",
      text: "مكان للتمهل والاستمتاع بالأحبة وصنع الذكريات حول البحر والشمس وراحة منزل خاص.",
      items: [
        { name: "الاسترخاء", text: "مسبح وحديقة وفضاءات خارجية.", alt: "مسبح خاص محاط بأشجار الزيتون" },
        { name: "المشاركة", text: "فضاءات مناسبة للحظات مع العائلة أو الأصدقاء.", alt: "طاولة معدّة في الخارج تحت العريشة" },
        { name: "الاكتشاف", text: "الاستمتاع بتازركة ومحيطها الساحلي.", alt: "باب أزرق تقليدي على جدار أبيض" },
      ],
    },
    booking: {
      title1: "إقامتك",
      title2: "تبدأ من هنا.",
      text: "لمعرفة التوفر وتنظيم إقامتكم، تواصلوا مباشرة مع CASA FIRMA.",
      wa: "احجز عبر WhatsApp",
      call: "اتصل بنا",
    },
    contact: {
      eyebrow: "اتصل بنا",
      title1: "تجدون كازا فيرما",
      title2: "في تازركة.",
      addressLabel: "العنوان",
      phoneLabel: "رقم الهاتف",
      instaLabel: "Instagram",
      maps: "فتح خرائط Google",
      call: "اتصل بنا",
      wa: "WhatsApp",
      insta: "تابعنا على Instagram",
      mapNote: "موقع تقريبي — افتح خرائط Google للاتجاهات.",
    },
    footer: {
      tagline: "دار ضيافة",
      city: "تازركة، تونس",
      links: "التنقل",
      social: "الشبكات",
      contact: "اتصل بنا",
      rights: "© 2026 CASA FIRMA",
    },
  },
} as const;
